apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specifies NLB type
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"  # Target type is IP (for EKS)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # Internet-facing
    service.beta.kubernetes.io/aws-load-balancer-id: "ml-app-nlb"  # Manually created load balancer name
spec:
  selector:
    app: ml-app
  ports:
    - protocol: TCP
      port: 5000  # Exposed port on the NLB
      targetPort: 5000  # Port on the container
  type: LoadBalancer
