apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: 156041445270.dkr.ecr.us-east-1.amazonaws.com/ml-app:latest
        ports:
        - containerPort: 5000
        # Optional: Add environment variables here if needed
        env:
        - name: FLASK_ENV
          value: production